/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package V_Admin;

import Class.DatabaseConnection;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Fauzanlh
 */
public class V_Tambah_Kategori extends javax.swing.JFrame {

    /**
     * Creates new form V_Tambah_Kategori
     */
    Connection koneksi;

    public V_Tambah_Kategori() {
        initComponents();
        this.setLocationRelativeTo(null);
        koneksi = DatabaseConnection.getKoneksi("localhost", "3306", "root", "", "db_kuliah_provis_perpustakaan");
        setKode();
    }

    public void Clear() {
        setKode();
        txtNamaKategori.setText("");
    }

    public void setKode() {
        try {
            Statement stmt = koneksi.createStatement();
            String Select = "SELECT * FROM t_Kategori_koleksi order by Kd_Kategori desc limit 1";
            ResultSet rs = stmt.executeQuery(Select);
            if (rs.next()) {
                txtKdKategori.setText("" + (rs.getInt("Kd_Kategori") + 1));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    public void SimpanData() {
        String KdKategori = txtKdKategori.getText().toUpperCase();
        String NamaKategori = txtNamaKategori.getText().toUpperCase();
        try {
            Statement stmt = koneksi.createStatement();
            if (!KdKategori.equals("") && !NamaKategori.equals("")) {
                String SqlUbahPassword = "INSERT INTO t_Kategori_koleksi VALUES('" + KdKategori + "','" + NamaKategori + "')";
                int BerhasilUpdate = stmt.executeUpdate(SqlUbahPassword);
                if (BerhasilUpdate == 1) {
                    System.out.println(SqlUbahPassword);
                    JOptionPane.showMessageDialog(null, "TAMBAH KATEGORI BERHASIL DILAKUKAN");
                    Clear();
                } else {
                    System.out.println(SqlUbahPassword);
                    JOptionPane.showMessageDialog(null, "TAMBAH KATEGORI GAGAL DILAKUKAN");
                }
            } else {
                if (KdKategori.equals("")) {
                    JOptionPane.showMessageDialog(null, "KODE KATEGORI HARUS DI ISI");
                    txtKdKategori.requestFocus();
                } else if (NamaKategori.equals("")) {
                    JOptionPane.showMessageDialog(null, "NAMA KATEGORI HARUS DI ISI");
                    txtNamaKategori.requestFocus();
                } else {
                    JOptionPane.showMessageDialog(null, "FORM HARUS DI ISI");
                    txtKdKategori.requestFocus();
                }
            }
        } catch (SQLException e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel1 = new javax.swing.JPanel();
        PanelDirectory = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        FormUbah = new javax.swing.JPanel();
        lblNoPol1 = new javax.swing.JLabel();
        txtKdKategori = new javax.swing.JTextField();
        lblNoPol2 = new javax.swing.JLabel();
        txtNamaKategori = new javax.swing.JTextField();
        btnClearPass = new javax.swing.JButton();
        btnUBah = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        mainPanel1.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel1.setPreferredSize(new java.awt.Dimension(710, 673));

        PanelDirectory.setBackground(new java.awt.Color(30, 130, 234));
        PanelDirectory.setPreferredSize(new java.awt.Dimension(636, 100));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Master/Tambah Kategori");

        javax.swing.GroupLayout PanelDirectoryLayout = new javax.swing.GroupLayout(PanelDirectory);
        PanelDirectory.setLayout(PanelDirectoryLayout);
        PanelDirectoryLayout.setHorizontalGroup(
            PanelDirectoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDirectoryLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel9)
                .addContainerGap(87, Short.MAX_VALUE))
        );
        PanelDirectoryLayout.setVerticalGroup(
            PanelDirectoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDirectoryLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(39, 39, 39))
        );

        FormUbah.setBackground(new java.awt.Color(255, 255, 255));
        FormUbah.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tambah Kategori", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 16), new java.awt.Color(51, 51, 51))); // NOI18N
        FormUbah.setForeground(new java.awt.Color(51, 51, 51));
        FormUbah.setPreferredSize(new java.awt.Dimension(337, 189));

        lblNoPol1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNoPol1.setForeground(new java.awt.Color(51, 51, 51));
        lblNoPol1.setText("Kode Kategori");

        txtKdKategori.setEditable(false);
        txtKdKategori.setBackground(new java.awt.Color(255, 255, 255));
        txtKdKategori.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtKdKategori.setForeground(new java.awt.Color(51, 51, 51));
        txtKdKategori.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        lblNoPol2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNoPol2.setForeground(new java.awt.Color(51, 51, 51));
        lblNoPol2.setText("Nama Kategori");

        txtNamaKategori.setBackground(new java.awt.Color(255, 255, 255));
        txtNamaKategori.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtNamaKategori.setForeground(new java.awt.Color(51, 51, 51));
        txtNamaKategori.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        javax.swing.GroupLayout FormUbahLayout = new javax.swing.GroupLayout(FormUbah);
        FormUbah.setLayout(FormUbahLayout);
        FormUbahLayout.setHorizontalGroup(
            FormUbahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormUbahLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FormUbahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNoPol1)
                    .addComponent(lblNoPol2))
                .addGap(18, 18, 18)
                .addGroup(FormUbahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtKdKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNamaKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        FormUbahLayout.setVerticalGroup(
            FormUbahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormUbahLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(FormUbahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNoPol1)
                    .addComponent(txtKdKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(FormUbahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNamaKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNoPol2))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        btnClearPass.setBackground(new java.awt.Color(240, 240, 240));
        btnClearPass.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnClearPass.setForeground(new java.awt.Color(51, 51, 51));
        btnClearPass.setText("Clear");
        btnClearPass.setBorder(null);
        btnClearPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearPassActionPerformed(evt);
            }
        });

        btnUBah.setBackground(new java.awt.Color(240, 240, 240));
        btnUBah.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnUBah.setForeground(new java.awt.Color(51, 51, 51));
        btnUBah.setText("Submit");
        btnUBah.setBorder(null);
        btnUBah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUBahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanel1Layout = new javax.swing.GroupLayout(mainPanel1);
        mainPanel1.setLayout(mainPanel1Layout);
        mainPanel1Layout.setHorizontalGroup(
            mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(FormUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(mainPanel1Layout.createSequentialGroup()
                .addComponent(PanelDirectory, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClearPass, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUBah, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
        mainPanel1Layout.setVerticalGroup(
            mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(PanelDirectory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(FormUbah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUBah, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClearPass, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(mainPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearPassActionPerformed
        Clear();
    }//GEN-LAST:event_btnClearPassActionPerformed

    private void btnUBahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUBahActionPerformed
        SimpanData();
    }//GEN-LAST:event_btnUBahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(V_Tambah_Kategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(V_Tambah_Kategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(V_Tambah_Kategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(V_Tambah_Kategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new V_Tambah_Kategori().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FormUbah;
    private javax.swing.JPanel PanelDirectory;
    private javax.swing.JButton btnClearPass;
    private javax.swing.JButton btnUBah;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblNoPol1;
    private javax.swing.JLabel lblNoPol2;
    private javax.swing.JPanel mainPanel1;
    private javax.swing.JTextField txtKdKategori;
    private javax.swing.JTextField txtNamaKategori;
    // End of variables declaration//GEN-END:variables
}
